### ISSUE TITLE
Issues encountered by newcomers

### ISSUE THREAD

**Issue by peterwaller-arm** [elfshaker/elfshaker#10]
A list of things we should make sure are clearly documented.

If you're new to rust:

- [x] You might not know to use `--release` with `cargo build`.
- [x] Unclear that a freshly built binary lives under target/release/elfshaker.

(I believe these items are documented, and we'll also provide release binaries on the releases page).

If you're new to elfshaker:
- [x] #7 are pretty easy to hit if you make a typo and it's not clear what is wrong.
  - This was improved in #68, if you hit an unclear error, please report it.
- [x] ~Obtaining the packfiles and putting them in the right directory structure is a little annoying.~
  - (Fixed by introduction of 'elfshaker clone' in #75, now you can clone a URL and simply list and extract all snapshots; packfiles are fetched under the hood on demand).
- [x] ~Some commands require you specify a packfile. If the snapshot is unambiguous, I think we should make sure this is not required (if I understand correctly).~
  - Fixed in #84.

**Comment by Aceeri** [comment]
Could just set `opt-level=3`on [profile.dev] for the `--release` issue. Although it wouldn't change that it goes to a different target directory.
