### ISSUE TITLE
Add --snapshots-from <file> to `pack` command

### ISSUE THREAD

**Issue by marxin** [elfshaker/elfshaker#100]
Please add `--snapshots-from` in `pack` command so that one can select a subset of snapshots that are packed.

**Comment by peterwaller-arm** [comment]
Sounds good to me. This is the code that would need updating. Someone may implement this over the coming months, if anyone is interested in taking a crack at it please shout and/or take assignment.

https://github.com/elfshaker/elfshaker/blob/1755d4fc69d6af519f562f7cdc9a822443c3859a/src/bin/elfshaker/pack.rs#L64-L66

**Comment by Mistuke** [comment]
Created https://github.com/elfshaker/elfshaker/pull/102 to address this.
