### ISSUE TITLE
`extract` from a NFS read-only filesystem

### ISSUE THREAD

**Issue by marxin** [elfshaker/elfshaker#109]
I would like to provide `eflshaker` binaries as a read-only NFS filesystem, but apparently, one can't extract from such a filesystem type:

```
$ /home/mliska/Programming/elfshaker/target/release/elfshaker --data-dir /mnt/gcc-binaries/elfshaker_data extract 97f3003f6f7f1710245307d0dc989955ad59e957 --verify --reset
[ERROR (main) 674.20893ms]: *FATAL*: couldn't create or open /mnt/gcc-binaries/elfshaker_data/trash/85e8effd66bd3a2c2818eab249fc744e for writing (ReadOnlyFilesystem)
```

**Comment by peterwaller-arm** [comment]
What's happening is that we're updating the `HEAD` in the repository to point at the chosen commit. The trash hash is a temporary file where we write the new head before atomically updating it with a `rename()`.

For me this relates to https://github.com/elfshaker/elfshaker/issues/92 and the fact you're having to do a reset.

So we have three bits of state:

1) The files as they appear in the 'extracted' working directory.
2) The 'HEAD' file which points to the last thing that was extracted (only meaningful if we've extracted before).
3) The pack files.

One git equivalent would be that you can specify an objects(/packs) directory independently from a repository. Or that we should allow extracting without updating the repository state. So, extract into an empty directory, referring to an existing elfshaker_data (so you can share packs with it) without writing an elfshaker_data into the directory being extracted into.

This is a bit of user experience I would like to improve, I think referencing an existing repository without updating it is a useful thing, as is creating an 'extracted' directory without the addition of an elfshaker_data directory.

Possible actions:

1) Make the packs directory configurable (via environment?) independently from elfshaker_data
2) Add a flag to extract (`--no-update-head`?) to avoid touching the original repository
3) Add a flag controlling which directory is extracted to, perhaps for the use case of extracting an existing repository to an new or empty directory.
4) Think harder about this.

Currently I'm leaning towards (3/4), input is appreciated.

**Comment by marxin** [comment]
I like any both 2) and 3) which would work for me. It sounds to me a bit related to `git workspace` concept, where you have expanded multiple versions of a repository.

**Comment by peterwaller-arm** [comment]
If you want it urgently and are up for having a go at implementing such a thing I would review/accept such a pull request efficiently, assuming it is close-to-trivial and there is no unexpected complexity-of-implementation blow-up. Otherwise it will likely be a while before I get around to it.

**Comment by marxin** [comment]
Sorry, I can't write in Rust, thus I'm leaving that to you guys. I can wait for sure.

**Comment by peterwaller-arm** [comment]
Should be working after #124.
