### ISSUE TITLE
Negative compression levels are advertised but not supported

### ISSUE THREAD

**Issue by LilithHafner** [elfshaker/elfshaker#117]
```
shell> ../elfshaker/target/release/elfshaker pack my_pack --help
elfshaker-pack 
Packs the given snapshots into a pack file.

...

OPTIONS:
        --compression-level <compression-level>
            The level of compression to use (between -131072 and 22) [default: 22]
...

shell> ../elfshaker/target/release/elfshaker pack my_pack --compression-level -25
error: Found argument '-2' which wasn't expected, or isn't valid in this context

USAGE:
    elfshaker pack <name> --compression-level <compression-level>

For more information try --help
```

Also, [-131072, 22] is a highly unusual range of values. I would recommend normalizing to 0–100 or something more common unless there is a specific reason to use this specific range of compression levels, and if there is a specific reason, it would be good to document that so that folks know what to make of this range of available compression levels.

**Comment by peterwaller-arm** [comment]
See also #87.

I agree that -131072 looks weird. My understanding is that it is meant to be supported by zstd but at glance it looks like we have a parse bug on the command line. I'd be fine with fixing the bug or dropping support for negative levels. Any comments from anyone else?

**Comment by veselink1** [comment]
Also agreed -- the range of values appears unusual. But all of the values in the range have meaning.

See https://news.ycombinator.com/item?id=31429533 and the linked GitHub issue. 

>  Levels < 0 are the "fast" compression levels. They achieve speed by turning off Huffman compression, and by "accelerating" compression by a factor. Level -1 has acceleration factor 1, -2 has acceleration factor 2, and so on. So the minimum supported negative compression level is -131072, since the maximum acceleration factor is our block size. But in practice, I wouldn't think a negative level lower than -10 or -20 would be all that useful.

I'm happy to set a lower bound if that would reduce confusion, but I'd like to keep the negative levels. I think part of the confusion comes from the fact that ZStandard does not document the negative lower bound (but the upper bound is mentioned in docs). 

Therefore, I think keeping the upper bound of 22 in the help is not unreasonable.
