### ISSUE TITLE
Compression level 22 is a very bad default in some cases

### ISSUE THREAD

**Issue by LilithHafner** [elfshaker/elfshaker#118]
When compressing 8 random somewhat recent builds of Julia into a single pack, elshaker seemed to hang. Lowering the compression level fixed the issue. I sampled a sweep of compression levels from 0 to 14 and found that anywhere from 0–10 would be a reasonable default for my use case, but 22, the current default, is way outside the realm of viable compression levels.

<img width="937" alt="Screenshot 2023-08-13 at 8 27 29 AM copy" src="https://github.com/elfshaker/elfshaker/assets/60898866/e9f5c68e-cf3d-43b4-bed7-18b05bc82590">

For compression levels between 0 and 10, compression ratio is between 5.3 and 5.9, and runtime is between 15 and 47 seconds. Bringing the compression level up to 14, however, increases the compression ratio to 6.0 (a negligible increase) in exchange for increasing the runtime to 7.6 minutes (a major regression). If the exponential fit generalizes, it would take 20 hours to compress these 8 versions at compression level 22. I didn't wait to find out.

<details>

<summary>versions of Julia I was compressing</summary>

```
f4101e949300fc40375a21b24f842bc06464c3d2
3b81696a88abd778660fdda282328bce45974e21
cbbcf07f1f9cf18165eca5ac8985cd780c1e2dd5
27201e5de0a46f96ed0c2d6c4f5883d45729b1e2
c63feee3bc3eb1f8433cb03a8cf85af39c0f05d3
5e8e0a51908ae3050890e870c69aa1fdbb2e3761
4084f7ebec63cf9b6a53f3a12df91bbf0c0a4161
5544a0fab7648cfa61fe79cd557a7504a92ec1b5
```

</details>

**Comment by peterwaller-arm** [comment]
@LilithHafner thank you for raising this, I agree with you. In our case the compressed size was about ~150MiB and we were aiming to squeeze out every megabyte, so the long runtime was tolerable enough. But I agree that this doesn't generalise and is a bad default. I'd be happy if you could recommend a default and I think we could run with it.

Apart from anything else I think a lower value gives a much better interactive experience if you're first experimenting with elfshaker -- the packing operation can be very quick at the lower levels and time is of the essence if one is doing a quick experiment for viability.

**Comment by peterwaller-arm** [comment]
The default was changed to 10 in #120, hope that's better. I'm still open to lowering the default further if someone makes a case for it. The current value is chosen to be a tradeoff made on the assumption that packs are likely to be retransmitted a fair amount, so it's worth spending a bit of CPU to pack. Also, that the machines building packs (and thus building lots of software) are likely to be many core machines to make the build take a reasonable amount of time, so I'm assuming there is a reasonable amount of CPU available.

**Comment by LilithHafner** [comment]
Lovely, thank you! My usecasea doesn't involve retransmission, so I'll probably go a little lower than 10, but 10 is still quite viable for my usecase and seems like a sensible default.
