### ISSUE TITLE
Compression level help weirdness

### ISSUE THREAD

**Issue by peterwaller-arm** [elfshaker/elfshaker#26]
```
OPTIONS:
        --compression-level <compression-level>
            The level of compression to use (between -131072 and 22) [default: 22]
```

The minimum value isn't correct, I think it should be 1.

**Comment by veselink1** [comment]
This appears to be the correct range for Zstandard. Negative values (fast compression) are supported and specified with `--fast=` for the CLI. 
https://github.com/facebook/zstd/pull/1332
https://github.com/facebook/zstd

**Comment by peterwaller-arm** [comment]
Closing as not-a-bug, since this is actually a feature of zstd.
