### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by peterwaller-arm** [elfshaker/elfshaker#31]
We could provide a one-liner install script. I'm thinking something which wgets the a tarball and untars it to `~/.local` or `$prefix` if set -- I'm imagining the tarball would contain a musl-built elfshaker binary and manpages.

**Comment by veselink1** [comment]
One-liner install script added in https://github.com/elfshaker/elfshaker/pull/42. 
Adding manpages is tracked by https://github.com/elfshaker/elfshaker/issues/32.
