### ISSUE TITLE
Poor 'file not found' errors

### ISSUE THREAD

**Issue by peterwaller-arm** [elfshaker/elfshaker#7]
Unfortunately when a File::open fails due to a missing file, it does not report an informative error about which file is missing.

I think we should wrap all File::open calls with something that decorates such errors with the filename, so that the user knows what the problem is. I've hit this a couple of times and haven't been able to work out what is wrong without editing the code.

**Comment by bolshoytoster** [comment]
I can probably do this

**Comment by veselink1** [comment]
@bolshoytoster Thanks, it would be really nice if you could take a look.

**Comment by bolshoytoster** [comment]
I’ve opened a pull request (#64)
