### ISSUE TITLE
Instructions on building `compdb2line`

### ISSUE THREAD

**Issue by mattgodbolt** [elfshaker/elfshaker#76]
When running `manyclangs-build-month` it says "Note that compdb2line is part of this project and needs installing." - I can't find any reference on how to do this.

There's some `.go` files in `contrib/compdb2line`. I install `eflshaker` from source with `cargo install --path .` There's no other reference to `compdb2line` in the repo I can find - how might I build and install this tool?

**Comment by veselink1** [comment]
Hey Matt, so glad to see you're giving elfshaker a test run. Sorry about the missing instructions. You will need a go toolchain (the Ubuntu package is `golang-go`) and just run `go build` in `contrib/compdb2line` and you should get a statically-linked executable.

**Comment by mattgodbolt** [comment]
NM that's it :)
