### ISSUE TITLE
Support changing of the elfshaker_data directory.

### ISSUE THREAD

**Issue by Mistuke** [elfshaker/elfshaker#86]
I'd like to be able to support changing of the `elfshaker_data` directory so I can place it outside of the current build folder.

This makes it easier when a partial rebuild fails and one has to wipe the build directory to do a full one.
Additionally it'll also make it easier to store the build directory on an external drive.

**Comment by peterwaller-arm** [comment]
I have the exact use case. I'll pick this up but it may still be Sept onwards before I get to it.

**Comment by peterwaller-arm** [comment]
This has landed in #88.
