### ISSUE TITLE
Weird compression level range

### ISSUE THREAD

**Issue by marxin** [elfshaker/elfshaker#87]
Thanks for the tool! I noticed:

```
elfshaker pack --help
elfshaker-pack 
Packs the given snapshots into a pack file.

USAGE:
    elfshaker pack [FLAGS] [OPTIONS] <name> [indexes]...

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
        --verbose    Enables verbose description of the execution process.

OPTIONS:
        --compression-level <compression-level>
            The level of compression to use (between -131072 and 22) [default: 22]
```

Seems `-131072` is a weird compression level, isn't it?

**Comment by veselink1** [comment]
We thought it was a bug too, initially. But apparently, Zstd (which is what we use internally) supports negative compression levels up to -131072.

http://facebook.github.io/zstd/zstd_manual.html
https://www.ibm.com/docs/en/psfa/7.2.1?topic=details-compress-option
