### ISSUE TITLE
manyclangs: git-list-between incomplete output for 2022-08

### ISSUE THREAD

**Issue by peterwaller-arm** [elfshaker/elfshaker#89]
`git-list-between` stops after llvm/llvm-project@ef110a491f70, giving a date range of 2022-08-11 through to the end of the month, so I am currently unable to build the August pack.

Repro with git commands:

```
$ TZ=UTC git log --since=2022/08/01 --format=fuller ef110a491f702e84d3f97e7cde6dacea99fd238d -- llvm clang
commit ef110a491f70
AuthorDate: Thu Aug 11 12:29:01 2022 +0100
CommitDate: Thu Aug 11 12:29:01 2022 +0100
```

The output stops here.

The reason it stops is that there is a non clang/llvm commit in LLDB with a `CommitDate` date of Sept 14 2021. The only way I can see that happening is if the computer used to push the commit had an incorrect clock.

To fix this we need to consider more commits going backwards in time, and not just stop at the first commit out of the desired date range. I suppose it should be enough to 'terminate the walk once we have seen N commits with a timestamp which is too old' to account for the occasional clock mishap, or simply to consider all commits before taking the subset we're interested in (for some small CPU-seconds expense, I imagine).

There is a minor consideration -- if this had happened to a clang/llvm commit that was going into a pack, it'd have a September 2021 date on it, but in the August 2022 pack. Which would be a little bit weird, but if you consider the packs as 'ranges of the dag', I think it is fine. Additionally this is a pretty big break the assumption 'lexical order on date is commit order', but this is only a convenience that I don't think anything depends on in a significant way.

I'll fix this at the next convenient moment but time is extremely limited in the coming weeks, so it may have to wait. If someone else fancies taking up the mantle, we just need the output of:

```
$ git-list-between origin/main 2022/08/01 2022/09/01 -- clang llvm
```

To start at 2022-08-01 and end on 2022-08-30. Please message or assign yourself if you intend to take a look.

**Comment by veselink1** [comment]
> break the assumption 'lexical order on date is commit order'

IIRC, we don't really assume that anywhere. The snapshot order in the pack is the same as the commit/build order. We do, however, sort the output automatically as of #85. Before #85, the output by list would reflect the correct commit order. The information is also not lost -- we have the generation number in the snapshot tag.

**Comment by peterwaller-arm** [comment]
I don't think the sorted output list would reflect commit order. Because yes, there is a generation number in there, but the date can be 'wrong' and reflect a commit in a different month, imagine sorting this for example:

```
20220812-1234-gitcommit
20210901-1235-gitcommit
20220812-1236-gitcommit
```

The information is still not lost by virtue of the pack though, so I guess that's OK.

**Comment by veselink1** [comment]
> I don't think the sorted output list would reflect commit order.

The sorted output wouldn't. I was making the point that sorting the output is a recent change that we could revert.
