### ISSUE TITLE
elfshaker looses executable flag on files

### ISSUE THREAD

**Issue by marxin** [elfshaker/elfshaker#93]
```
$ echo XXX > A && chmod 755 A
$ ls -l A
-rwxr-xr-x 1 marxin users 4 Sep 15 12:43 A
$ elfshaker store one
$ rm A
$ elfshaker extract one --reset
A 	1 files
D 	0 files
M 	0 files
Extracted 'loose/one:one'
$ ls -l A
-rw-r--r-- 1 marxin users 4 Sep 15 12:44 A
```

**Comment by marxin** [comment]
@Mistuke

**Comment by peterwaller-arm** [comment]
This is #13, but happy to leave this open. It's tricky since it will require extra information in the index and a new index format. Definitely something we want to address I think.

**Comment by marxin** [comment]
Maybe you can sneak in a few bits in the current index format. What do you think? Is the problem related only to the executable flag, or the flags as well?

**Comment by peterwaller-arm** [comment]
It's all of the mode bits. Yes, I think the information can be put in there in principle, with effort. Can't promise a timescale at the moment, apologies.

**Comment by peterwaller-arm** [comment]
I have a draft PR to implement this at #107.

**Comment by peterwaller-arm** [comment]
This should be fixed on master and we're preparing to make a release before too long, sorry for the wait, it has been a spare time project :)
